#!/usr/bin/env bash
# Bash script to connect to a server without typing a password
Host 18.233.63.155
    HostName 18.233.63.155
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no

